### ISSUE TITLE
Cannot find module '../node_modules/jspm/lib/config.js'

### ISSUE THREAD

**Issue by feimosi** [pauldijou/outdated#3]
I get this error even when trying to disable jspm with command-line parameters

``` sh
Error: Cannot find module '../node_modules/jspm/lib/config.js'                                    
    at Function.Module._resolveFilename (module.js:339:15)                                        
    at Function.Module._load (module.js:290:25)                                                   
    at Module.require (module.js:367:17)                                                          
    at require (internal/module.js:16:19)                                                         
    at Object.<anonymous> (F:\CS\node_modules\outdated\lib\jspm.js:12:18) 
    at Module._compile (module.js:413:34)                                                         
    at Object.Module._extensions..js (module.js:422:10)                                           
    at Module.load (module.js:357:32)                                                             
    at Function.Module._load (module.js:314:12)                                                   
    at Module.require (module.js:367:17)                                                          
    at require (internal/module.js:16:19)                                                         
    at Object.<anonymous> (F:\CS\node_modules\outdated\index.js:15:9)     
    at Module._compile (module.js:413:34)                                                         
    at Object.Module._extensions..js (module.js:422:10)                                           
    at Module.load (module.js:357:32)                                                             
    at Function.Module._load (module.js:314:12)                                                   
```

**Comment by pauldijou** [comment]
I'm sorry, I don't really have time to work on this project right now. I will try to find some as soon as possible.

**Comment by feimosi** [comment]
I understand, no problem.
